---

variables:
  MY_PROJECT_ID: "57036704"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/netbox_content.git"
  # PAGES_ENVIRONMENT_PATH: projects/ansible/collection/kubernetes/
  # RELEASE_ADDITIONAL_ACTIONS_BUMP: ./.gitlab/additional_actions_bump.sh


include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/automagic.gitlab-ci.yaml


Update Git Submodules:
  extends: .ansible_playbook_git_submodule
